# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

# CI build producing developer packages.
resources:
  repositories:
  - repository: PipelineTools
    type: git
    endpoint: ToolsAccess
    name: tools.internal
    ref: 78ecf591964ecf511b4c7a0cd84d98ce11e8be16

pr: none # disable PR validation
trigger:
  tags:
    include:
    - '*'
  branches:
    exclude:
    - main

jobs:
- job: UnityValidation
  pool: Unity_2021.3.3f1_Pool
  steps:
  - checkout: self
  
  - checkout: PipelineTools
  
  - pwsh: Write-Host "##vso[build.updatebuildnumber]$(Version)"
    displayName: 'Set Build Number'

  - task: ComponentGovernanceComponentDetection@0
    inputs:
      scanType: 'Register'
      alertWarningLevel: 'Medium'
      failOnAlert: true

  - template: Templates/upm.yaml
    parameters:
      publishToFeed: true